export const defaultSteps = [
  {
    name: 'Aguardando peças',
    description: 'Peças solicitadas e aguardando chegada',
  },
  { name: 'Desmontagem', description: 'Realizando desmontagem' },
  { name: 'Diagnóstico', description: 'Realizando diagnóstico' },
  { name: 'Troca de óleo', description: 'Realizando troca de óleo' },
  { name: 'Troca de pneus', description: 'Realizando troca de pneus' },
  { name: 'Troca de bateria', description: 'Realizando troca de bateria' },
  { name: 'Troca de pastilhas', description: 'Realizando troca de pastilhas' },
  { name: 'Troca de filtros', description: 'Realizando troca de filtros' },
  { name: 'Troca de correias', description: 'Realizando troca de correias' },
  { name: 'Troca de velas', description: 'Realizando troca de velas' },
  {
    name: 'Troca de amortecedores',
    description: 'Realizando troca de amortecedores',
  },
  { name: 'Troca de embreagem', description: 'Realizando troca de embreagem' },
  {
    name: 'Troca de escapamento',
    description: 'Realizando troca de escapamento',
  },
  { name: 'Troca de radiador', description: 'Realizando troca de radiador' },
  {
    name: "Troca de bomba d'água",
    description: "Realizando troca de bomba d'água",
  },
  {
    name: 'Troca de bomba de combustível',
    description: 'Realizando troca de bomba de combustível',
  },
  {
    name: 'Troca de bomba de óleo',
    description: 'Realizando troca de bomba de óleo',
  },
  { name: 'Troca de sensor', description: 'Realizando troca de sensor' },
  {
    name: 'Troca de termostato',
    description: 'Realizando troca de termostato',
  },
  { name: 'Troca de junta', description: 'Realizando troca de junta' },
  {
    name: 'Troca de correia dentada',
    description: 'Realizando troca de correia dentada',
  },
  {
    name: 'Troca de rolamentos',
    description: 'Realizando troca de rolamentos',
  },
  { name: 'Troca de molas', description: 'Realizando troca de molas' },
  { name: 'Troca de buchas', description: 'Realizando troca de buchas' },
  { name: 'Troca de pivôs', description: 'Realizando troca de pivôs' },
  { name: 'Troca de coxins', description: 'Realizando troca de coxins' },
  { name: 'Troca de batentes', description: 'Realizando troca de batentes' },
  { name: 'Troca de bandejas', description: 'Realizando troca de bandejas' },
  {
    name: 'Troca de caixa de direção',
    description: 'Realizando troca de caixa de direção',
  },
  {
    name: 'Troca de bomba de direção',
    description: 'Realizando troca de bomba de direção',
  },
  {
    name: 'Troca de mangueiras',
    description: 'Realizando troca de mangueiras',
  },
  { name: 'Troca de cabos', description: 'Realizando troca de cabos' },
  { name: 'Troca de bobinas', description: 'Realizando troca de bobinas' },
  { name: 'Troca de módulos', description: 'Realizando troca de módulos' },
  { name: 'Troca de central', description: 'Realizando troca de central' },
  { name: 'Troca de sensores', description: 'Realizando troca de sensores' },
  { name: 'Troca de chicotes', description: 'Realizando troca de chicotes' },
  { name: 'Troca de bicos', description: 'Realizando troca de bicos' },
  { name: 'Troca de bombas', description: 'Realizando troca de bombas' },
  { name: 'Troca de válvulas', description: 'Realizando troca de válvulas' },
  { name: 'Troca de atuadores', description: 'Realizando troca de atuadores' },
  { name: 'Troca de tensores', description: 'Realizando troca de tensores' },
  { name: 'Troca de polias', description: 'Realizando troca de polias' },
  {
    name: 'Troca de engrenagens',
    description: 'Realizando troca de engrenagens',
  },
  { name: 'Troca de disco', description: 'Realizando troca de disco' },
  { name: 'Troca de platô', description: 'Realizando troca de platô' },
  { name: 'Troca de cilindros', description: 'Realizando troca de cilindros' },
  { name: 'Troca de tambores', description: 'Realizando troca de tambores' },
  { name: 'Troca de lonas', description: 'Realizando troca de lonas' },
  { name: 'Remontagem', description: 'Realizando remontagem' },
  { name: 'Teste de rodagem', description: 'Realizando teste de rodagem' },
  { name: 'Finalizado', description: 'Serviço finalizado' },
];
